USE [master]
GO

/****** Object:  Database [HyveHR]    Script Date: 04/07/2026 19:20:47 ******/
CREATE DATABASE [HyveHR]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HyveHR_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\HyveHR.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HyveHR_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\HyveHR.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HyveHR].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HyveHR] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HyveHR] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HyveHR] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HyveHR] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HyveHR] SET ARITHABORT OFF 
GO

ALTER DATABASE [HyveHR] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HyveHR] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HyveHR] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HyveHR] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HyveHR] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HyveHR] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HyveHR] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HyveHR] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HyveHR] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HyveHR] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HyveHR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HyveHR] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HyveHR] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HyveHR] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HyveHR] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HyveHR] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HyveHR] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HyveHR] SET RECOVERY FULL 
GO

ALTER DATABASE [HyveHR] SET  MULTI_USER 
GO

ALTER DATABASE [HyveHR] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HyveHR] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HyveHR] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HyveHR] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [HyveHR] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HyveHR] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [HyveHR] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [HyveHR] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HyveHR] SET  READ_WRITE 
GO

